apiVersion: v1
kind: Service
metadata:
  name: {{ include "cromwell.fullname" . }}-job-manager-service
spec:
  type: LoadBalancer
  selector:
    app: {{ include "cromwell.fullname" . }}-job-manager-deployment
  ports:
  - name: jm-ui
    protocol: TCP
    port: 80
    targetPort: 80
