apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "cromwell.fullname" . }}-job-manager-api-configuration2
data:
  api-config.json: |
    {
        "cromwell_user":"{{ .Values.jobManager.cromwellUser }}",
        "cromwell_password":"{{ .Values.jobManager.cromwellPass }}"
    }
  capabilities-config.json: |
      {
          "displayFields": [
            {
              "field": "status",
              "display": "Status"
            },
            {
              "field": "submission",
              "display": "Submitted"
            },
            {
              "field": "end",
              "display": "End Time"
            },
            {
              "field": "labels.cromwell-workflow-id",
              "display": "Workflow ID"
            },
            {
              "field": "labels.comment",
              "display": "Comment",
              "fieldType": "text",
              "editable": true,
              "bulkEditable": true
            },
            {
              "field": "labels.flag",
              "display": "Flag",
              "editable": true,
              "bulk_editable": true,
              "fieldType": "list",
              "validFieldValues": ["archive", "follow-up"]
            }
          ],
          "commonLabels": [
            "cromwell-workflow-id",
            "workflow-name",
            "comment",
            "flag"
          ],
          "queryExtensions": [],
          "authentication": {
            "isRequired": false,
            "scopes": [
              "openid",
              "email",
              "profile"
            ]
          }
          }
