apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cromwell.fullname" . }}-summarizer
  labels:
    app.kubernetes.io/name: {{ include "cromwell.name" . }}-summarizer
    helm.sh/chart: {{ include "cromwell.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: 1
  #TODO: What does this mean?
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "cromwell.name" . }}-summarizer
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "cromwell.name" . }}-summarizer
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          args: ["server"]
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 30
            httpGet:
              path: /
              port: http
          readinessProbe:
            initialDelaySeconds: 80
            httpGet:
              path: /
              port: http
          resources:
          env:
              - name: JAVA_OPTS
                value: "-Dconfig.file=/conf/cromwell-summarizer.conf"
              - name: METADATA_LOG_MODE
                value: "FILEROLLER"
              - name: METADATA_FILEROLLER_DIR
                value: "/shared"
          volumeMounts:
            - name: config-volume
              mountPath: /conf
            - name: shared-data
              mountPath: /shared
      volumes:
        - name: shared-data
          emptyDir: {}
        - name: config-volume
          configMap:
            name: {{ template "cromwell.fullname" . }}-configuration
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
