apiVersion: v1
kind: Pod
metadata:
  name: mysql-proxy-pod
  labels:
      app: mysql-proxy
spec:
  containers:
    - name: mysql-proxy-container
      args: ["/cloud_sql_proxy", "-instances=broad-dsde-cromwell-dev:us-east4-c:db-kube2=tcp:0.0.0.0:3306", "-credential_file=/conf/mysql-sa.json"]
      image: gcr.io/cloudsql-docker/gce-proxy:1.13
      ports:
          - containerPort: 3306
            hostPort: 3306
      volumeMounts:
        - name: config-volume
          mountPath: /conf
  volumes:
    - name: config-volume
      configMap:
        # Provide the name of the ConfigMap containing the files you want
        # to add to the container
        name: rw
