apiVersion: v1
kind: Pod
metadata:
  name: varnish-cache
  labels:
      app: varnish-cache
spec:
  containers:
  - name: cache
    resources:
      requests:
        # We'll use two gigabytes for each varnish cache
        memory: 2Gi
    image: danbills/varnish:6_1
    imagePullPolicy: Always
    args: ["-F", "-f", "/conf/varnish-rw-cromwell-config.vcl", "-a" , "0.0.0.0:8080" , "-s" , "malloc,2G"]
    ports:
    - containerPort: 8080
    volumeMounts:
    - name: config-volume
      mountPath: /conf
  volumes:
    - name: config-volume
      configMap:
        # Provide the name of the ConfigMap containing the files you want
        # to add to the container
        name: rw
